# Generated by Django 6.0.2 on 2026-03-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('receiver', 'Receiver'), ('hospital', 'Hospital')], default='receiver', max_length=10),
        ),
    ]
