# Generated by Django 4.2.28 on 2026-02-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personprofile',
            name='organ',
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_required', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('medical_report', models.FileField(upload_to='organ_requests/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('medical_report', models.FileField(upload_to='donation_requests/')),
                ('status', models.CharField(default='Available', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personprofile')),
            ],
        ),
    ]
