# Generated by Django 6.0.2 on 2026-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organtracking',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('in_transit', 'In Transit'), ('transplanted', 'Transplanted')], default='available', max_length=50),
        ),
    ]
