# Generated by Django 6.0.2 on 2026-02-16 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('medical_report', models.TextField()),
                ('status', models.CharField(default='Available', max_length=50)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('urgency_level', models.CharField(max_length=20)),
                ('medical_report', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_status', models.CharField(default='Matched', max_length=50)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organdonation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organrequest')),
            ],
        ),
    ]
