# Generated by Django 6.0.2 on 2026-02-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organdonation_organrequest_organmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organdonation')),
            ],
        ),
    ]
