# Generated by Django 6.0.2 on 2026-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organmatch',
            name='match_status',
            field=models.CharField(default='proposed', max_length=50),
        ),
    ]
