# Generated by Django 6.0.2 on 2026-02-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_organtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organrequest',
            name='urgency_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
    ]
