# Generated by Django 6.0.2 on 2026-03-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_organtracking_status'),
        ('users', '0003_alter_organmatch_match_status'),
    ]

    operations = [
    ]
