# Generated by Django 6.0.2 on 2026-03-01 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_organrequest_urgency_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organrequest',
            name='organ_type',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='organ',
        ),
        migrations.AddField(
            model_name='organrequest',
            name='organ_required',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='medical_report',
            field=models.FileField(upload_to='organ_requests/'),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personprofile'),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='urgency_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('medical_report', models.FileField(upload_to='donation_requests/')),
                ('status', models.CharField(default='Available', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.personprofile')),
            ],
        ),
        migrations.AlterField(
            model_name='organmatch',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.donationrequest'),
        ),
        migrations.AlterField(
            model_name='organtracking',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.donationrequest'),
        ),
        migrations.DeleteModel(
            name='OrganDonation',
        ),
    ]
