# Generated by Django 6.0.2 on 2026-03-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260308_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organtracking',
            name='status',
            field=models.CharField(choices=[('Ready for Transport', 'Ready for Transport'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Arrived at Receiver Hospital', 'Arrived at Receiver Hospital'), ('Handed Over to Surgery Team', 'Handed Over to Surgery Team'), ('Transplant Completed', 'Transplant Completed')], default='Ready for Transport', max_length=50),
        ),
    ]
