# Generated by Django 6.0.2 on 2026-03-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260309_0022'),
        ('users', '0005_alter_organtracking_status'),
    ]

    operations = [
    ]
