# Generated by Django 6.0.2 on 2026-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260309_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organmatch',
            name='match_status',
            field=models.CharField(default='Proposed', max_length=50),
        ),
    ]
