# Generated by Django 6.0.2 on 2026-03-01 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contactmessage_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organtracking',
            name='organ',
        ),
        migrations.AddField(
            model_name='organtracking',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organmatch'),
        ),
    ]
