# Generated by Django 4.2.28 on 2026-03-02 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_organtracking_organ_organtracking_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='license_number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='license_number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='organ',
            field=models.CharField(choices=[('Heart', 'Heart'), ('Lung', 'Lung'), ('Liver', 'Liver'), ('Kidney', 'Kidney'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine'), ('Cornea', 'Cornea'), ('Bone Marrow', 'Bone Marrow'), ('Skin', 'Skin'), ('Bone', 'Bone'), ('Heart Valve', 'Heart Valve')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='organ_required',
            field=models.CharField(blank=True, choices=[('Heart', 'Heart'), ('Lung', 'Lung'), ('Liver', 'Liver'), ('Kidney', 'Kidney'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine'), ('Cornea', 'Cornea'), ('Bone Marrow', 'Bone Marrow'), ('Skin', 'Skin'), ('Bone', 'Bone'), ('Heart Valve', 'Heart Valve')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organtracking',
            name='current_location',
            field=models.CharField(default='At Donor Hospital', max_length=255),
        ),
        migrations.AlterField(
            model_name='organtracking',
            name='status',
            field=models.CharField(default='Ready for Transport', max_length=50),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
