# Generated by Django 6.0.2 on 2026-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_organmatch_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organmatch',
            name='donor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organmatch',
            name='receiver_approved',
            field=models.BooleanField(default=False),
        ),
    ]
